LOBBY-SERVER: 'Hub'

SCOREBOARD:
  TITLE: "&b&lExample &7| &fSUMO"
  LOBBY:
    - "&7&m-----------------------"
    - "&fOnline: &b<online_players>"
    - "&fPlaying: &b<match_players>"
    - " "
    - "&7dev.frozed.club"
    - "&7&m-----------------------"
  MATCH:
    - "&7&m-----------------------"
    - "&fOpponent: &b<opponent>"
    - "&fKit: &bSumo"
    - " "
    - "&fPing: &b<player_ping> &7┃ &b<opponent_ping>"
    - "&fCPS: &b<player_cps> &7┃ &b<opponent_cps>"
    - " "
    - "&7dev.frozed.club"
    - "&7&m-----------------------"
  MATCH-END:
    - "&7&m-----------------------"
    - "&fMatch ended"
    - "&fLoser: &b<opponent>"
    - " "
    - "&7dev.frozed.club"
    - "&7&m-----------------------"