name: FrozedSumo
main: club.frozed.frozedsumo.FrozedSumo
description: FrozedSumo - Practice-like core for Sumo
version: 2.1-RECODE
author: Elb1to
website: www.frozed.club
commands:
  sumo:
  arena:
  setspawn:
  duel: